/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'size' : string,
  'productId' : bigint,
  'quantity' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'principal' : Principal,
  'total' : number,
  'paymentMethod' : string,
  'createdAt' : bigint,
  'items' : Array<CartItem>,
}
export interface Product {
  'id' : bigint,
  'originalPrice' : number,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'discount' : bigint,
  'category' : string,
  'isNew' : boolean,
  'price' : number,
}
export interface _SERVICE {
  'addCartItem' : ActorMethod<[CartItem], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCartItems' : ActorMethod<[], Array<CartItem>>,
  'getCategoryProducts' : ActorMethod<[string], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getNewArrivals' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'isInWishlist' : ActorMethod<[bigint], boolean>,
  'placeOrder' : ActorMethod<[string], Order>,
  'removeCartItem' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];